# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0006_auto_20180216_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='painting/%Y/%m/%d')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('creation_year', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('material', models.CharField(max_length=100)),
                ('technique', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('genre', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
    ]
