# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-18 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='profile.Profile'),
        ),
    ]
