# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_auto_20180318_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='cost',
            field=models.PositiveIntegerField(default=247456),
            preserve_default=False,
        ),
    ]
