# Generated by Django 2.0.3 on 2018-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0003_painting_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='colour',
        ),
        migrations.AddField(
            model_name='painting',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='painting',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='painting',
            name='material',
            field=models.CharField(default='холст', max_length=100),
        ),
    ]
