# Generated by Django 2.0.3 on 2018-03-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0004_auto_20180321_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='cost',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='painting',
            name='creation_year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='painting',
            name='genre',
            field=models.CharField(choices=[('Абстракционизм', 'Абстракционизм'), ('Гиперреализм', 'Гиперреализм'), ('Городской пейзаж', 'Городской пейзаж'), ('Импрессионизм', 'Импрессионизм'), ('Классицизм', 'Классицизм'), ('Морской пейзаж', 'Морской пейзаж'), ('Натюрморт', 'Натюрморт'), ('Пейзаж', 'Пейзаж'), ('Портрет', 'Портрет'), ('Сюрреализм', 'Сюрреализм')], max_length=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='technique',
            field=models.CharField(choices=[('Масло', 'Масло'), ('Гуашь', 'Гуашь'), ('Пастель', 'Пастель'), ('Тушь', 'Тушь'), ('Акварель', 'Акварель')], max_length=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
