# Generated by Django 2.0.3 on 2018-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0005_auto_20180321_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='painting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
