# Generated by Django 2.0.3 on 2018-03-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20180321_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
