# Generated by Django 2.0.3 on 2018-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20180321_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
