# Generated by Django 2.0.3 on 2018-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_auto_20180321_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='имя пользователя'),
        ),
    ]
