# Generated by Django 2.0.3 on 2018-03-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20180326_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_yourself',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/%Y/%m/%d', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='статус'),
        ),
    ]
